<a href="https://colab.research.google.com/github/Ronaknowal/Python/blob/main/Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
list1=[1,2,3]
type(list1)

list

In [2]:
import numpy as np
arr=np.array([123])
type(arr)

numpy.ndarray

In [3]:
print(arr)
print(list1)

[123]
[1, 2, 3]


In [14]:
arr.ndim

1

In [12]:
np.arange(4,13)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
range(4,13)

range(4, 13)

In [17]:
for i in range(4,13):
  print(i)

4
5
6
7
8
9
10
11
12


In [19]:
np.arange(1,13,3)

array([ 1,  4,  7, 10])

In [22]:
np.arange(7,14,2,dtype=float)

array([ 7.,  9., 11., 13.])

In [23]:
np.arange(7,14,2,float)

array([ 7.,  9., 11., 13.])

In [24]:
np.linspace(3,13,4)

array([ 3.        ,  6.33333333,  9.66666667, 13.        ])

In [26]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [27]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.zeros(4),np.ones(6)

(array([0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1.]))

In [35]:
arr2=[2,3,4,56,22,5,6,24,5]

In [36]:
max(arr2)

56

In [37]:
arr2=np.array(arr2)

In [39]:
max(arr2)

56

In [38]:
arr2.argmax() #position of the max value

3

In [41]:
arr2.argmin() #position of the min value

0

In [42]:
arr2

array([ 2,  3,  4, 56, 22,  5,  6, 24,  5])

In [44]:
arr2[1]=100

In [46]:
arr2

array([  2, 100,   4,  56,  22,   5,   6,  24,   5])

In [47]:
arr2[2:6],arr2[3:7]

(array([ 4, 56, 22,  5]), array([56, 22,  5,  6]))

In [49]:
arr3=np.array([[1,2,3],[4,5,6]])

In [50]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr3[1][2]

6

In [57]:
arr4=np.array([[[1,2,3],[4,5,6],[3,4,7]]])

In [58]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [3, 4, 7]]])

In [62]:
arr4[0]

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 7]])

In [63]:
arr4[0][1][0:2]

array([4, 5])

In [65]:
arr5=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])

In [66]:
arr5.ndim

5

In [71]:
arr6=np.arange(12)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
arr6.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
arr6.sum()

66

In [88]:
np.random.rand(5)

array([0.16969505, 0.70640742, 0.72935737, 0.30128799, 0.44962569])

In [89]:
np.random.randint(100)

79

In [90]:
np.sqrt(4)

2.0

In [91]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [92]:
np.sqrt(arr5)

array([[[[[1.        , 1.41421356, 1.73205081],
          [2.        , 2.23606798, 2.44948974],
          [2.64575131, 2.82842712, 3.        ]]]]])

In [93]:
np.log(arr5)

array([[[[[0.        , 0.69314718, 1.09861229],
          [1.38629436, 1.60943791, 1.79175947],
          [1.94591015, 2.07944154, 2.19722458]]]]])

In [94]:
np.log10(arr5)

array([[[[[0.        , 0.30103   , 0.47712125],
          [0.60205999, 0.69897   , 0.77815125],
          [0.84509804, 0.90308999, 0.95424251]]]]])

In [95]:
a=-30

In [97]:
np.abs(a)

30

In [99]:
b=[2,3,-6,-2,1,-2,5]
np.abs(b)

array([2, 3, 6, 2, 1, 2, 5])

In [102]:
c=np.array(b)
c

array([ 2,  3, -6, -2,  1, -2,  5])

In [104]:
np.abs(c)

array([2, 3, 6, 2, 1, 2, 5])

# Pandas -- Data Manupulation

  pandas--->1) Series & 2) DataFrame

In [105]:
import pandas as pd

In [108]:
s=pd.Series(np.random.rand(6))
s

0    0.326329
1    0.991424
2    0.454576
3    0.490630
4    0.515347
5    0.084741
dtype: float64

In [109]:
s[3]

0.4906299391567387

In [110]:
s[2:4]

2    0.454576
3    0.490630
dtype: float64

In [111]:
s[0]=12
s

0    12.000000
1     0.991424
2     0.454576
3     0.490630
4     0.515347
5     0.084741
dtype: float64

In [113]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [116]:
s.index=['a','b','c','d','e',3]

In [117]:
s

a    12.000000
b     0.991424
c     0.454576
d     0.490630
e     0.515347
3     0.084741
dtype: float64

In [118]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 3], dtype='object')

In [119]:
s['b']

0.9914237935429119

In [121]:
s['b':]

b    0.991424
c    0.454576
d    0.490630
e    0.515347
3    0.084741
dtype: float64

In [122]:
s['b':'e']

b    0.991424
c    0.454576
d    0.490630
e    0.515347
dtype: float64

In [124]:
# code:   s[2]
# output: keyerror

In [125]:
s[2:5]

c    0.454576
d    0.490630
e    0.515347
dtype: float64

In [127]:
s[-5:-1]

b    0.991424
c    0.454576
d    0.490630
e    0.515347
dtype: float64

In [128]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 3], dtype='object')

In [129]:
s['a':'e':2]

a    12.000000
c     0.454576
e     0.515347
dtype: float64

In [131]:
s1=pd.Series(np.random.rand(12))
s1

0     0.818124
1     0.792255
2     0.667684
3     0.655126
4     0.415710
5     0.711351
6     0.942259
7     0.258997
8     0.391729
9     0.910606
10    0.781561
11    0.871485
dtype: float64

In [132]:
s1[1:9:2]

1    0.792255
3    0.655126
5    0.711351
7    0.258997
dtype: float64

In [138]:
s2=pd.Series(np.random.rand(6))
s3=pd.Series(np.random.rand(6))
s2,s3

(0    0.572459
 1    0.386580
 2    0.790167
 3    0.795647
 4    0.494234
 5    0.127759
 dtype: float64,
 0    0.662019
 1    0.828163
 2    0.113810
 3    0.413232
 4    0.018182
 5    0.756639
 dtype: float64)

In [140]:
df=pd.DataFrame([s2,s3])
df

0         1         2         3         4         5
0  0.572459  0.386580  0.790167  0.795647  0.494234  0.127759
1  0.662019  0.828163  0.113810  0.413232  0.018182  0.756639

In [142]:
df.T

0         1
0  0.572459  0.662019
1  0.386580  0.828163
2  0.790167  0.113810
3  0.795647  0.413232
4  0.494234  0.018182
5  0.127759  0.756639