<a href="https://colab.research.google.com/github/Ronaknowal/Python/blob/main/Numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
list1=[1,2,3]
type(list1)

list

In [2]:
import numpy as np
arr=np.array([1,2,3])
type(arr)

numpy.ndarray

In [3]:
print(arr)
print(list1)

[1 2 3]
[1, 2, 3]


In [4]:
arr.ndim

1

In [9]:
np.arange(4,13)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
range(4,13)

range(4, 13)

In [11]:
for i in range(4,13):
  print(i)

4
5
6
7
8
9
10
11
12


In [12]:
np.arange(1,13,3)

array([ 1,  4,  7, 10])

In [13]:
np.arange(7,14,2,dtype=float)

array([ 7.,  9., 11., 13.])

In [14]:
np.arange(7,14,2,float)

array([ 7.,  9., 11., 13.])

In [15]:
np.linspace(3,13,4)

array([ 3.        ,  6.33333333,  9.66666667, 13.        ])

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros(4),np.ones(6)

(array([0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1.]))

In [19]:
arr2=[2,3,4,56,22,5,6,24,5]

In [20]:
max(arr2)

56

In [21]:
arr2=np.array(arr2)

In [22]:
max(arr2)

56

In [23]:
arr2.argmax() #position of the max value

3

In [24]:
arr2.argmin() #position of the min value

0

In [25]:
arr2

array([ 2,  3,  4, 56, 22,  5,  6, 24,  5])

In [26]:
arr2[1]=100

In [27]:
arr2

array([  2, 100,   4,  56,  22,   5,   6,  24,   5])

In [28]:
arr2[2:6],arr2[3:7]

(array([ 4, 56, 22,  5]), array([56, 22,  5,  6]))

In [29]:
arr3=np.array([[1,2,3],[4,5,6]])

In [30]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr3[1][2]

6

In [32]:
arr3.ndim

2

In [33]:
arr4=np.array([[[1,2,3],[4,5,6],[3,4,7]]])

In [34]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [3, 4, 7]]])

In [35]:
arr4[0]

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 7]])

In [36]:
arr4[0][1][0:2]

array([4, 5])

In [37]:
arr4.ndim

3

In [38]:
arr5=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])

In [39]:
arr5.ndim

5

In [40]:
arr6=np.arange(12)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
arr6.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
arr6.sum()

66

In [50]:
np.random.rand(5)

array([0.35174468, 0.48384403, 0.87905073, 0.50544757, 0.74273008])

In [51]:
np.random.randint(100)

49

In [52]:
np.sqrt(4)

2.0

In [53]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [54]:
np.sqrt(arr5)

array([[[[[1.        , 1.41421356, 1.73205081],
          [2.        , 2.23606798, 2.44948974],
          [2.64575131, 2.82842712, 3.        ]]]]])

In [55]:
np.log(arr5)

array([[[[[0.        , 0.69314718, 1.09861229],
          [1.38629436, 1.60943791, 1.79175947],
          [1.94591015, 2.07944154, 2.19722458]]]]])

In [56]:
np.log10(arr5)

array([[[[[0.        , 0.30103   , 0.47712125],
          [0.60205999, 0.69897   , 0.77815125],
          [0.84509804, 0.90308999, 0.95424251]]]]])

In [57]:
a=-30

In [58]:
np.abs(a)

30

In [59]:
b=[2,3,-6,-2,1,-2,5]
np.abs(b)

array([2, 3, 6, 2, 1, 2, 5])

In [60]:
c=np.array(b)
c

array([ 2,  3, -6, -2,  1, -2,  5])

In [61]:
np.abs(c)

array([2, 3, 6, 2, 1, 2, 5])

# Pandas -- Data Manupulation

  pandas--->1) Series & 2) DataFrame

In [62]:
import pandas as pd

In [63]:
s=pd.Series(np.random.rand(6))
s

0    0.189359
1    0.787554
2    0.897046
3    0.306703
4    0.196276
5    0.633478
dtype: float64

In [64]:
s[3]

0.3067027307636141

In [65]:
s[2:4]

2    0.897046
3    0.306703
dtype: float64

In [66]:
s[0]=12
s

0    12.000000
1     0.787554
2     0.897046
3     0.306703
4     0.196276
5     0.633478
dtype: float64

In [67]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [68]:
s.index=['a','b','c','d','e',3]

In [69]:
s

a    12.000000
b     0.787554
c     0.897046
d     0.306703
e     0.196276
3     0.633478
dtype: float64

In [70]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 3], dtype='object')

In [71]:
s['b']

0.7875536928271317

In [72]:
s['b':]

b    0.787554
c    0.897046
d    0.306703
e    0.196276
3    0.633478
dtype: float64

In [73]:
s['b':'e']

b    0.787554
c    0.897046
d    0.306703
e    0.196276
dtype: float64

In [74]:
# code:   s[2]
# output: keyerror

In [75]:
s[2:5]

c    0.897046
d    0.306703
e    0.196276
dtype: float64

In [76]:
s[-5:-1]

b    0.787554
c    0.897046
d    0.306703
e    0.196276
dtype: float64

In [77]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 3], dtype='object')

In [78]:
s['a':'e':2]

a    12.000000
c     0.897046
e     0.196276
dtype: float64

In [79]:
s1=pd.Series(np.random.rand(12))
s1

0     0.470694
1     0.455723
2     0.357498
3     0.231427
4     0.811323
5     0.433651
6     0.808450
7     0.662464
8     0.350951
9     0.615859
10    0.066592
11    0.030495
dtype: float64

In [80]:
s1[1:9:2]

1    0.455723
3    0.231427
5    0.433651
7    0.662464
dtype: float64

In [81]:
s2=pd.Series(np.random.rand(6))
s3=pd.Series(np.random.rand(6))
s2,s3

(0    0.423094
 1    0.092158
 2    0.022773
 3    0.128667
 4    0.018973
 5    0.263480
 dtype: float64,
 0    0.360629
 1    0.021476
 2    0.424557
 3    0.726704
 4    0.881044
 5    0.519460
 dtype: float64)

In [82]:
df=pd.DataFrame([s2,s3])
df

0         1         2         3         4        5
0  0.423094  0.092158  0.022773  0.128667  0.018973  0.26348
1  0.360629  0.021476  0.424557  0.726704  0.881044  0.51946

In [93]:
df=df.T
df

0         1
0  0.423094  0.360629
1  0.092158  0.021476
2  0.022773  0.424557
3  0.128667  0.726704
4  0.018973  0.881044
5  0.263480  0.519460

In [94]:
df.columns = ['s1','s2']
df

s1        s2
0  0.423094  0.360629
1  0.092158  0.021476
2  0.022773  0.424557
3  0.128667  0.726704
4  0.018973  0.881044
5  0.263480  0.519460

In [95]:
Friends={'Name':['Sid','khushi','SK','Priyam'], 'Gender':['M','F','M','M']}

In [96]:
df=pd.DataFrame(Friends)

In [97]:
df

Name Gender
0     Sid      M
1  khushi      F
2      SK      M
3  Priyam      M

In [98]:
df['Uni']=['VIT','VIT','VIT','VIT'];

In [100]:
df

Name Gender  Uni
0     Sid      M  VIT
1  khushi      F  VIT
2      SK      M  VIT
3  Priyam      M  VIT

In [102]:
df['age']=['19','20','20','29']

In [103]:
df

Name Gender  Uni age
0     Sid      M  VIT  19
1  khushi      F  VIT  20
2      SK      M  VIT  20
3  Priyam      M  VIT  29

In [104]:
df['age']=['19','20','20',np.nan]

In [105]:
df

Name Gender  Uni  age
0     Sid      M  VIT   19
1  khushi      F  VIT   20
2      SK      M  VIT   20
3  Priyam      M  VIT  NaN

In [108]:
df.drop(['Uni','age'],axis=1)

Name Gender
0     Sid      M
1  khushi      F
2      SK      M
3  Priyam      M

In [109]:
df=df.drop(['Uni'],axis=1)

In [111]:
df.loc[0:3,'Gender':] # Actual row and column as a parameter

Gender  age
0      M   19
1      F   20
2      M   20
3      M  NaN

In [112]:
df.iloc[0:2,0:1] # Actual index of row and column as a parameter

Name
0     Sid
1  khushi

In [113]:
df.loc[4]=['Sujay','M','21']

In [114]:
df

Name Gender  age
0     Sid      M   19
1  khushi      F   20
2      SK      M   20
3  Priyam      M  NaN
4   Sujay      M   21

In [117]:
df.loc['Shera']=['Shubham',np.nan,'22']

In [118]:
df

Name Gender  age
0          Sid      M   19
1       khushi      F   20
2           SK      M   20
3       Priyam      M  NaN
4        Sujay      M   21
Shera  Shubham    NaN   22

In [119]:
df.drop(['Shera'],axis=0)

Name Gender  age
0     Sid      M   19
1  khushi      F   20
2      SK      M   20
3  Priyam      M  NaN
4   Sujay      M   21

In [120]:
df

Name Gender  age
0          Sid      M   19
1       khushi      F   20
2           SK      M   20
3       Priyam      M  NaN
4        Sujay      M   21
Shera  Shubham    NaN   22

In [123]:
df.isnull()

Name  Gender    age
0      False   False  False
1      False   False  False
2      False   False  False
3      False   False   True
4      False   False  False
Shera  False    True  False

In [124]:
df.isnull().sum()

Name      0
Gender    1
age       1
dtype: int64

In [127]:
df['intAge']=[19,20,20,np.nan,21,22]

In [128]:
df['intAge'].sum()

102.0

In [129]:
df.sum()

<ipython-input-129-7e5fdb616c56>:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.sum()


Name      SidkhushiSKPriyamSujayShubham
intAge                            102.0
dtype: object

In [131]:
df['intAge'].dtype

dtype('float64')

In [133]:
print(df['age'].dtype)
print(df['Name'].dtype)
print(df['Gender'].dtype)

object
object
object


In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to Shera
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    6 non-null      object 
 1   Gender  5 non-null      object 
 2   age     5 non-null      object 
 3   intAge  5 non-null      float64
dtypes: float64(1), object(3)
memory usage: 412.0+ bytes


In [136]:
df.describe()

intAge
count   5.000000
mean   20.400000
std     1.140175
min    19.000000
25%    20.000000
50%    20.000000
75%    21.000000
max    22.000000

In [137]:
df.describe(include='all')

Name Gender  age     intAge
count     6      5    5   5.000000
unique    6      2    4        NaN
top     Sid      M   20        NaN
freq      1      4    2        NaN
mean    NaN    NaN  NaN  20.400000
std     NaN    NaN  NaN   1.140175
min     NaN    NaN  NaN  19.000000
25%     NaN    NaN  NaN  20.000000
50%     NaN    NaN  NaN  20.000000
75%     NaN    NaN  NaN  21.000000
max     NaN    NaN  NaN  22.000000

In [139]:
df['intAge'].mean()

20.4

In [140]:
df['intAge'].median()

20.0

In [141]:
df['intAge'].std()

1.1401754250991378

In [145]:
df

Name Gender  age  intAge
0          Sid      M   19    19.0
1       khushi      F   20    20.0
2           SK      M   20    20.0
3       Priyam      M  NaN     NaN
4        Sujay      M   21    21.0
Shera  Shubham    NaN   22    22.0

In [168]:
df=pd.read_csv('insurance.csv')

In [169]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [170]:
df.tail()

age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [171]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [172]:
df.shape

(1338, 7)

In [173]:
df.ndim

2

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [175]:
df.isnull()

age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [176]:
df.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

In [177]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [178]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [180]:
df.region.unique() # gives all the unique values in that column

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [181]:
df.region.unique().shape

(4,)

In [183]:
df.sex.unique()

array(['female', 'male'], dtype=object)

In [184]:
df.smoker.unique()

array(['yes', 'no'], dtype=object)

In [185]:
df.region.value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

In [186]:
df.sex.value_counts()

male      676
female    662
Name: sex, dtype: int64

In [187]:
df.smoker.value_counts()

no     1064
yes     274
Name: smoker, dtype: int64

In [189]:
df.corr()

<ipython-input-189-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000